title: Samuel Diaz
description: > # this means to ignore newlines until "baseurl:"
  
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sdiaz1924.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Samuel Diaz # add your name
author-img: samdiaz.JPG # add your photo
about-author: I am a MPP graduate of the University of Chicago Harris School of Public Policy and a Performance Analyst at the City of Chicago Office of Inspector General. I'm a firm believer in using data and technology to address the world's most pressing policy challenges. <p> I'm a first generation college graduate, an underrepresented minority, Arsenal F.C. fan, Chicago tavern-style pizza aficionado, and an avid cyclist/makeshift bike mechanic. <p> sdiaz1924 [at] gmail [dot] com # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: diazsamuel/ # add your Linkedin handle
social-email: sdiaz1924@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
